# Información general
site_name: 'Física'
site_description: 'Apuntes sobre física clásica'
site_author: 'Raul Jesus Lopez'
site_url: http://www.rauljesus.xyz/fisica

# Repositorio
repo_name: 'Ver en GitHub'
repo_url: 'https://github.com/la9una/fisica'

# Tema
theme:
  name: 'material'
  language: 'es'
  icon:
 #   logo: material/library
    logo: fontawesome/solid/graduation-cap
    repo: fontawesome/brands/git-alt
  palette:
    primary: 'light blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: true

# Extra
extra:
  disqus: 'rauljesus-xyz'
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/la9una'
    - icon: fontawesome/brands/facebook-f
      link: 'https://www.facebook.com/rauljesuslopez'
    - icon: fontawesome/brands/github
      link: 'https://github.com/la9una'

# Extensiones
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML


plugins:
  - search # necessary for search to work
  - git-revision-date-localized:
      type: date

######################################################################
### DOCUMENTACIÓN ####################################################
######################################################################

# Páginas
nav: 
- Inicio: 'index.md'
#- Mediciones: 
#    - Introducción: 'mediciones/index.md'
#    - Equivalencias: 'mediciones/equivalencias.md'
#    - Teoría de errores: 'mediciones/calculoerror.md'
#    - Ejercicios: 'mediciones/ejercicios.md'

    #    - Sistema internacional de unidades: 'mediciones/si.md'
#    - Notación científica: 'mediciones/notacion.md'
#- Cinemática: 
#    - Introducción: 'cinematica/index.md'
#    - M.R.U.: 'cinematica/mru.md'
##    - M.R.U.V.: 'cinematica/mruv.md'
#    - Ejercicios: 'cinematica/ejercicios.md'
#- Dinámica: 
#    - Introducción: 'dinamica/index.md'
#- Trabajo y energía: 
#    - Introducción: 'energia/index.md'
#    - Energía Mecánica: 
#          - Conservación: 'energia/mecanica.md'
#          - Energía Cinética: 'energia/cinetica.md'
#          - Energía Potencial: 'energia/potencial.md'
#    - Trabajo: 'energia/trabajo.md'
#    - Energía Térmica: 'energia/termica.md'
#    - Ejercicios: 'energia/ejercicios.md'
- Anexos: 
    - Fórmulas: 'anexos/formulas.md'
    - Constantes: 'anexos/constantes.md'
    - Bibliografía: 'anexos/bibliografia.md'
    - Programas: 'anexos/programas.md'

#- Prácticas: 
#    - Laboratorio: 'practicas/laboratorio.md'
#    - Exposiciones: 'practicas/exposiciones.md'
