# Información general
site_name: 'Física'
site_description: 'Apuntes sobre física clásica'
site_author: 'Raul Jesus Lopez'
site_url: http://www.rauljesus.xyz/fisica

# Repositorio
repo_name: 'Ver en GitHub'
repo_url: 'https://github.com/la9una/fisica'

# Copyright
copyright: '2018 &nbsp; Raul Jesus Lopez'

# Tema
theme:
  name: 'material'
  language: 'es'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
#  feature:
#    tabs: true

# Extra
extra:
  search:
    language: 'es, en'
  disqus: 'rauljesus-xyz'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/la9una'
    - type: 'facebook'
      link: 'https://www.facebook.com/rauljesuslopez'
    - type: 'github'
      link: 'https://github.com/la9una'
#    - type: 'linkedin'
#      link: 'https://de.linkedin.com/in/john-doe'

## CSS Adicional
extra_css:
  - 'stylesheets/extra.css'

# Extensiones
markdown_extensions:
  - admonition
#  - codehilite(guess_lang=false,linenums=true)
#  - codehilite(guess_lang=false)
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML'


######################################################################
### DOCUMENTACIÓN ####################################################
######################################################################

# Páginas
nav: 
- Inicio: 'index.md'
- Mediciones: 
    - Introducción: 'mediciones/index.md'
    - Equivalencias: 'mediciones/equivalencias.md'
    - Teoría de errores: 'mediciones/calculoerror.md'
    - Ejercicios: 'mediciones/ejercicios.md'

    #    - Sistema internacional de unidades: 'mediciones/si.md'
#    - Notación científica: 'mediciones/notacion.md'
- Cinemática: 
    - Introducción: 'cinematica/index.md'
    - M.R.U.: 'cinematica/mru.md'
    - M.R.U.V.: 'cinematica/mruv.md'
    - Ejercicios: 'cinematica/ejercicios.md'
- Dinámica: 
    - Introducción: 'dinamica/index.md'
- Trabajo y energía: 
    - Introducción: 'energia/index.md'
    - Energía Mecánica: 
          - Conservación: 'energia/mecanica.md'
          - Energía Cinética: 'energia/cinetica.md'
          - Energía Potencial: 'energia/potencial.md'
    - Trabajo: 'energia/trabajo.md'
    - Energía Térmica: 'energia/termica.md'
    - Ejercicios: 'energia/ejercicios.md'

- Anexos: 
    - Fórmulas: 'anexos/formulas.md'
    - Constantes: 'anexos/constantes.md'
    - Bibliografía: 'anexos/bibliografia.md'

- Prácticas: 
    - Laboratorio: 'practicas/laboratorio.md'
    - Exposiciones: 'practicas/exposiciones.md'
