# Informaci칩n general
site_name: 'F&iacute;sica B&aacute;sica'
site_description: 'Introducci&oacute;n a la F&iacute;sica'
site_author: 'Raul Jesus Lopez'
site_url: http://www.rauljesus.xyz/fisica

# Repositorio
repo_name: 'Ver en GitHub'
repo_url: 'https://github.com/la9una/fisica'

# Copyright
#copyright: '2017 - Raul Jesus Lopez'

# Tema
theme: null
theme_dir: 'themes/material'

# Opciones
extra:
  palette:
    primary: 'green'
    accent: 'green'
  font:
    text: 'Roboto'
    code: 'PT Mono'
  social:
#    - type: 'github'
#      link: 'https://github.com/la9una'
    - type: 'twitter'
      link: 'https://twitter.com/la9una'
    - type: 'globe'
      link: http://rauljesus.com
#    - type: 'linkedin'
#      link: 'https://de.linkedin.com/in/john-doe'
#    - type: 'facebook'
#      link: 'https://www.facebook.com/rauljesuslopez'
  disqus: 'rauljesuscom'

# Google Analytics
google_analytics:
  - 'UA-98408177-1'
  - 'auto'

# Extensions
markdown_extensions:
  - pymdownx.arithmatex
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - footnotes
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

# Extras
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# P치ginas
pages: 
- Inicio: 'index.md'
- Mediciones: 
  - Introducci칩n: 'erroresIntroduccion.md'
  - Tipos de error: 'erroresTipos.md'
  - Propagaci칩n de errores: 'erroresPropagacion.md'
